--[[
SKIPPY_INSERT_SPELL, PLAYER_ENTERING_WORLD, PLAYER_STARTED_MOVING, PLAYER_STOPPED_MOVING, PLAYER_REGEN_DISABLED, PLAYER_REGEN_ENABLED, PLAYER_TALENT_UPDATE, PLAYER_SPECIALIZATION_CHANGED, ACTIVE_TALENT_GROUP_CHANGED, PLAYER_TOTEM_UPDATE, PLAYER_TARGET_CHANGED, PLAYER_FOCUS_CHANGED, PLAYER_DEAD, PLAYER_ALIVE, PLAYER_UNGHOST, PLAYER_MOUNT_DISPLAY_CHANGED, UPDATE_STEALTH, UPDATE_SHAPESHIFT_FORMS, UPDATE_SHAPESHIFT_FORM, UNIT_HEALTH, UNIT_MAXHEALTH, UNIT_HEAL_ABSORB_AMOUNT_CHANGED, UNIT_HEAL_PREDICTION, UNIT_POWER_UPDATE, UNIT_AURA, UNIT_SPELLCAST_SENT, UNIT_SPELLCAST_CHANNEL_START, UNIT_SPELLCAST_CHANNEL_STOP, UNIT_SPELLCAST_START, UNIT_SPELLCAST_STOP, UNIT_SPELLCAST_FAILED, UNIT_SPELLCAST_SUCCEEDED, UNIT_SPELLCAST_INTERRUPTED, UNIT_INVENTORY_CHANGED, SPELL_UPDATE_COOLDOWN, SPELL_UPDATE_CHARGES, TRAIT_CONFIG_UPDATED, GLYPH_ADDED, GLYPH_REMOVED, GLYPH_UPDATED, NAME_PLATE_UNIT_ADDED, NAME_PLATE_UNIT_REMOVED, ENCOUNTER_START, ENCOUNTER_END, BOSS_KILL, GROUP_ROSTER_UPDATE, UI_ERROR_MESSAGE
]]
function State(event,  arg1,  arg2,  arg3,  arg4)
    local handler = aura_env.handlers[event]

    if handler then
        handler(arg1,  arg2,  arg3,  arg4)
    end
end
